language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - chmod +x gradlew


script:
- "./gradlew build assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: aoZog+BffwZ6IyeTffxqJvBX4PyW0xddftif4+xKUuDRgcjC5Ndu0w8FiPDtTM4TCcwVD1zD7ryceOx/pE/TCQstfcTLGsCNrSS71TYAjz3WkOHZY8z2mUwQc6oCzxBcDc1i7YLlEMxQkORlJrqP22Z5XixrUY/MohQgXrbfPol+6/4n0fpqZsNkIn509awwDOy6my+3kuvuJjQd4l6YO25F+wqBeN2DZFEditAgH8kJ5Sgje7FXwZGUQAVjW8OgXlHEzGsZOmdQAQjRCA3H/GPQIH2cAdKp0IaFVGbH2SIUalDTjDgngZqCO9yJLuiJWuO2O8mLEAWsi9CHSzThpdKN0IjguDtL1y+qvR4tlZ1MeyNTmw6v0ZHaWPu4ERr1VGGH25dGhKojOvxx4Yv1NYQw4vBQu98EWBjEjQN/6iRJDKWyPK5mnnsBsVxxnrJfgpOAgCrCrLPdj6XpJf1pU/3NOT8Dirm45W7RTRRklGX5bdqCe1rWkJqzm4oaeFMYXMnw3LBwSuJ81rwVSlDbHKgNhyME1ZTL73Wdf39DsJ4Ab8VhCgUygnLuAN2F8hRjgHSrJXqkGppLpHp1Z4Z3Q5qEfbcJQb6Xke+4h8Cct+1y/NA4YNpU8UH3x45qP0GV5lr5inpKZmQSMcWQQvnn6TIN8ExPXnvXexxEOpYBD/U=
  file: ./app/build/outputs/apk/app-release-unsigned.apk
  on:
    repo: Madhurima94/madhu
